import Head from 'next/head'
import axios from "../components/axios";
import {useRouter} from "next/router";

export async function getServerSideProps(context) {
    const cookies = context.req.headers.cookie;
    if (!cookies || !cookies.split("=")[1]) {
        return {
            redirect: {
                destination: '/login',
                permanent: false
            }
        }
    }
    const response = await fetch("http://localhost:5000/api/users", {
        headers: {
            'Authorization': `Bearer ${cookies.split("=")[1]}`
        },
    })
    const data = await response.json()
    if (data.status === "error") {
        return {
            redirect: {
                destination: '/login',
                permanent: false
            }
        }
    }
    return {
        props: {data}
    }
}

export default function Home(props) {
    const router = useRouter()
    console.log(props)
    const logoutHandler = () => {
        axios.get('/users/logout').then(response => {
            console.log(response)
            router.replace('/')
        }).catch(error => {
            console.log(error)
        })
    }
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <button onClick={logoutHandler}>Log out</button>
            </main>
        </div>
    )
}
