import Head from 'next/head'

export async function getServerSideProps(context) {
    const cookies = context.req.headers.cookie;
    if (!cookies || !cookies.split("=")[1]) {
        return {
            redirect: {
                destination: '/login',
                permanent: false
            }
        }
    }
    const response = await fetch("http://localhost:5000/api/users", {
        headers: {
            'Authorization': `Bearer ${cookies.split("=")[1]}`
        },
    })
    const data = await response.json()
    if (data.status === "error") {
        return {
            redirect: {
                destination: '/login',
                permanent: false
            }
        }
    }
    return {
        props: {data}
    }
}

export default function Home(props) {
    console.log(props)
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>

            </main>
        </div>
    )
}
